const subjects = [
    "English",
    "Regional Languages",
    "Mathematics",
    "Science",
    "Social Sciences",
    "Physical Education",
    "Computer Basics",
    "Arts (Drawing)",
    "History",
    "Literature",
    "Philosophy",
    "Economics",
    "Geography",
    "Political Science",
    "Sociology",
    "Chemistry",
    "Physics",
    "Biology",
    "Others"
];